checksumBehavior: update

compressionLevel: mixed

enableGlobalCache: false

enableTelemetry: false

nodeLinker: node-modules

npmPublishAccess: public

pnpEnableEsmLoader: true

yarnPath: .yarn/releases/yarn-4.3.1.cjs
